#!/bin/bash

# Copyright AppsCode Inc. and Contributors
#
# Licensed under the AppsCode Community License 1.0.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/appscode/licenses/raw/1.0.0/AppsCode-Community-1.0.0.md
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Bake the tags from default-tags.env into the workflow_dispatch `default:`
# fields so they show up pre-filled in the GitHub "Run workflow" UI. GitHub
# cannot read a file for dispatch defaults at runtime, so we generate the
# inputs block between the BEGIN/END dispatch-defaults markers.
#
# Run this after editing default-tags.env, then commit the workflow change.

set -eou pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="${REPO_ROOT}/default-tags.env"
WF="${REPO_ROOT}/.github/workflows/collect-images.yml"

# input name | env var | description
INPUTS=(
    "appscode_cloud_tag|APPSCODE_CLOUD_TAG|appscode-cloud/installer tag (also names the output dir)"
    "kubedb_tag|KUBEDB_TAG|kubedb/installer tag"
    "kubestash_tag|KUBESTASH_TAG|kubestash/installer tag"
    "kubeops_tag|KUBEOPS_TAG|kubeops/installer tag"
    "kluster_manager_tag|KLUSTER_MANAGER_TAG|kluster-manager/installer tag"
    "open_viz_tag|OPEN_VIZ_TAG|open-viz/installer tag"
    "opnpulse_tag|OPNPULSE_TAG|opnpulse/installer tag"
)

declare -A VAL
if [ -f "${ENV_FILE}" ]; then
    while IFS='=' read -r k v; do
        [[ "${k}" =~ ^[A-Z_]+$ ]] || continue
        VAL["${k}"]="${v}"
    done < <(grep -E '^[A-Z_]+=' "${ENV_FILE}")
else
    echo "note: ${ENV_FILE} not found; defaults will be emptied" >&2
fi

block="$(mktemp)"
{
    echo "      # BEGIN dispatch-defaults (generated by hack/scripts/sync-dispatch-defaults.sh from default-tags.env)"
    for e in "${INPUTS[@]}"; do
        name="${e%%|*}"
        rest="${e#*|}"
        var="${rest%%|*}"
        desc="${rest##*|}"
        echo "      ${name}:"
        echo "        description: '${desc}'"
        echo "        required: true"
        echo "        default: '${VAL[${var}]:-}'"
    done
    echo "      # END dispatch-defaults"
} >"${block}"

awk -v blockfile="${block}" '
    /# BEGIN dispatch-defaults/ {
        while ((getline line < blockfile) > 0) print line
        skip=1
        next
    }
    /# END dispatch-defaults/ { skip=0; next }
    !skip { print }
' "${WF}" >"${WF}.tmp"
mv "${WF}.tmp" "${WF}"
rm -f "${block}"

echo "Synced dispatch defaults into ${WF}"
